fix extension compilation error for PG16
adjust/pg_type_template pull request #14
Opened 2024-07-30 12:40 UTC by ridvankorkmaz

There is a compilation problem for any extension generated by this template when extension is compiled for PostgreSQL 16.
At least following repositories are not compiled for PostgreSQL 16 and needed code change.
This PR corrects the error. See relevant ticket [DB-983](https://adjustcom.atlassian.net/browse/DB-983) for error details. 

F.Y.I @adjust/database-team @adjust/kpis-team 

[pg-ad_revenue_source](https://github.com/adjust/pg-ad_revenue_source)
[pg-match_type](https://github.com/adjust/pg-match_type)
[pg-purchase_verification_status](https://github.com/adjust/pg-purchase_verification_status)
[pg-rejected_engagement_type](https://github.com/adjust/pg-rejected_engagement_type)
[pg-sk_coarse_conversion_value](https://github.com/adjust/pg-sk_coarse_conversion_value)
[pg-sk_condition_type](https://github.com/adjust/pg-sk_condition_type)
[pg-subscription_event_type](https://github.com/adjust/pg-subscription_event_type)
[pg-unverified_install_reason](https://github.com/adjust/pg-unverified_install_reason)

2024-07-30 12:48 UTC, PerikAdjust approved these changes

2024-07-30 12:53 UTC, levakin commented
@ridvankorkmaz I've also noticed that these 2 extensions are also incompatible with PG 16: [pg-os_name](https://github.com/adjust/pg-os_name), [wltree](https://github.com/adjust/wltree)

e.g.
```
1.785 In file included from src/os_name.h:5,
1.785                  from src/os_name_v0_0.c:1:
1.785 src/os_name_v0_0.c: In function 'os_name_get_list':
1.785 src/os_name_v0_0.c:209:31: warning: passing argument 1 of 'PointerGetDatum' makes pointer from integer without a cast [-Wint-conversion]
1.785   209 |         PG_RETURN_ARRAYTYPE_P(makeArrayResult(astate, CurrentMemoryContext));
1.785       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.785       |                               |
1.785       |                               Datum {aka long unsigned int}
1.785 /usr/local/include/postgresql/server/fmgr.h:361:53: note: in definition of macro 'PG_RETURN_POINTER'
1.785   361 | #define PG_RETURN_POINTER(x) return PointerGetDatum(x)
...
```
wltree
```
1.581 ltree_io.c: In function 'ltree_in':
1.581 ltree_io.c:179:9: warning: implicit declaration of function 'SET_VARSIZE' [-Wimplicit-function-declaration]
1.581   179 |         SET_VARSIZE(result, LTREE_HDRSIZE + totallen);
1.581       |         ^~~~~~~~~~~
1.581 In file included from ltree.h:6,
1.581                  from ltree_io.c:10:
1.581 ltree_io.c: In function 'ltree_out':
1.581 /usr/local/include/postgresql/server/fmgr.h:241:9: warning: passing argument 1 of 'DatumGetPointer' makes integer from pointer without a cast [-Wint-conversion]
1.581   241 |         pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
1.581       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.581       |         |
1.581       |         struct varlena *
1.581 ltree.h:172:58: note: in expansion of macro 'PG_DETOAST_DATUM'
1.581   172 | #define PG_GETARG_LTREE(x)      ((ltree*)DatumGetPointer(PG_DETOAST_DATUM(PG_GETARG_DATUM(x))))
1.581       |                                                          ^~~~~~~~~~~~~~~~
1.581 ltree_io.c:198:26: note: in expansion of macro 'PG_GETARG_LTREE'
1.581   198 |         ltree      *in = PG_GETARG_LTREE(0);
1.581       |                          ^~~~~~~~~~~~~~~
1.581 In file included from ltree_io.c:6:
1.581 /usr/local/include/postgresql/server/postgres.h:312:23: note: expected 'Datum' {aka 'long unsigned int'} but argument is of type 'struct varlena *'
1.581   312 | DatumGetPointer(Datum X)
1.581       |                 ~~~~~~^
1.582 ltree_io.c:204:37: warning: implicit declaration of function 'VARSIZE' [-Wimplicit-function-declaration]
1.582   204 |         ptr = buf = (char *) palloc(VARSIZE(in));
1.582       |                                     ^~~~~~~
1.587 ltree_io.c: In function 'lquery_out':
1.587 /usr/local/include/postgresql/server/fmgr.h:241:9: warning: passing argument 1 of 'DatumGetPointer' makes integer from pointer without a cast [-Wint-conversion]
1.587   241 |         pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
1.587       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.587       |         |
1.587       |         struct varlena *
1.587 ltree.h:174:55: note: in expansion of macro 'PG_DETOAST_DATUM'
1.587   174 | #define PG_GETARG_LQUERY(x) ((lquery*)DatumGetPointer(PG_DETOAST_DATUM(PG_GETARG_DATUM(x))))
1.587       |                                                       ^~~~~~~~~~~~~~~~
1.587 ltree_io.c:637:26: note: in expansion of macro 'PG_GETARG_LQUERY'
1.587   637 |         lquery     *in = PG_GETARG_LQUERY(0);
1.587       |                          ^~~~~~~~~~~~~~~~
1.587 /usr/local/include/postgresql/server/postgres.h:312:23: note: expected 'Datum' {aka 'long unsigned int'} but argument is of type 'struct varlena *'
1.587   312 | DatumGetPointer(Datum X)
1.587       |                 ~~~~~~^
1.709 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden -DLOWER_NODE -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o ltree_op.o ltree_op.c
1.741 In file included from /usr/local/include/postgresql/server/utils/builtins.h:17,
1.741                  from ltree_op.c:13:
1.741 ltree_op.c: In function 'ltree_cmp':
1.741 /usr/local/include/postgresql/server/fmgr.h:241:9: warning: passing argument 1 of 'DatumGetPointer' makes integer from pointer without a cast [-Wint-conversion]
1.741   241 |         pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
1.741       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.741       |         |
1.741       |         struct varlena *
1.741 ltree.h:172:58: note: in expansion of macro 'PG_DETOAST_DATUM'
1.741   172 | #define PG_GETARG_LTREE(x)      ((ltree*)DatumGetPointer(PG_DETOAST_DATUM(PG_GETARG_DATUM(x))))
1.741       |                                                          ^~~~~~~~~~~~~~~~
1.741 ltree_op.c:90:19: note: in expansion of macro 'PG_GETARG_LTREE'
1.741    90 | ltree *a        = PG_GETARG_LTREE(0);                   \
1.741       |                   ^~~~~~~~~~~~~~~
1.741 ltree_op.c:99:9: note: in expansion of macro 'RUNCMP'
1.741    99 |         RUNCMP
1.741       |         ^~~~~~
1.741 In file included from ltree_op.c:6:
1.741 /usr/local/include/postgresql/server/postgres.h:312:23: note: expected 'Datum' {aka 'long unsigned int'} but argument is of type 'struct varlena *'
1.741   312 | DatumGetPointer(Datum X)
1.741       |                 ~~~~~~^
1.741 /usr/local/include/postgresql/server/fmgr.h:241:9: warning: passing argument 1 of 'DatumGetPointer' makes integer from pointer without a cast [-Wint-conversion]
1.741   241 |         pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
1.741       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.741       |         |
1.741       |         struct varlena *
1.741 ltree.h:172:58: note: in expansion of macro 'PG_DETOAST_DATUM'
1.741   172 | #define PG_GETARG_LTREE(x)      ((ltree*)DatumGetPointer(PG_DETOAST_DATUM(PG_GETARG_DATUM(x))))
1.741       |                                                          ^~~~~~~~~~~~~~~~
1.741 ltree_op.c:91:19: note: in expansion of macro 'PG_GETARG_LTREE'
1.741    91 | ltree *b        = PG_GETARG_LTREE(1);                   \
1.741       |                   ^~~~~~~~~~~~~~~
1.741 ltree_op.c:99:9: note: in expansion of macro 'RUNCMP'
1.741    99 |         RUNCMP
1.741       |         ^~~~~~
1.742 /usr/local/include/postgresql/server/postgres.h:312:23: note: expected 'Datum' {aka 'long unsigned int'} but argument is of type 'struct varlena *'
1.742   312 | DatumGetPointer(Datum X)
1.742       |                 ~~~~~~^
1.742 ltree_op.c: In function 'ltree_lt':
1.742 /usr/local/include/postgresql/server/fmgr.h:241:9: warning: passing argument 1 of 'DatumGetPointer' makes integer from pointer without a cast [-Wint-conversion]
1.742   241 |         pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
1.742       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1.742       |         |
1.742       |         struct varlena *
1.742 ltree.h:172:58: note: in expansion of macro 'PG_DETOAST_DATUM'
1.742   172 | #define PG_GETARG_LTREE(x)      ((ltree*)DatumGetPointer(PG_DETOAST_DATUM(PG_GETARG_DATUM(x))))
1.742       |                                                          ^~~~~~~~~~~~~~~~
1.742 ltree_op.c:90:19: note: in expansion of macro 'PG_GETARG_LTREE'
1.742    90 | ltree *a        = PG_GETARG_LTREE(0);                   \
1.742       |                   ^~~~~~~~~~~~~~~
1.742 ltree_op.c:106:9: note: in expansion of macro 'RUNCMP'
1.742   106 |         RUNCMP
1.742       |         ^~~~~~ [...]

2024-07-30 12:56 UTC, PerikAdjust commented
For wltree, I started to work on it https://github.com/adjust/wltree/pull/27
but I'm stuck with something and I didn't find the time right now to fix it.

2024-07-30 13:05 UTC, ridvankorkmaz commented
@levakin Thanks for contribution, 
[wltree](https://github.com/adjust/wltree) have different kind of problem (this PR does not cover but we have solution for this as well, @PerikAdjust mentioned), I update list with adding `wltree`

2024-07-30 13:18 UTC, levakin commented
@ridvankorkmaz does [pg-os_name](https://github.com/adjust/pg-os_name) have the same issue? It's not in the list.

2024-07-30 13:20 UTC, ridvankorkmaz commented
> @ridvankorkmaz does [pg-os_name](https://github.com/adjust/pg-os_name) have the same issue? It's not in the list.

Yes, I updated the list with `wltree`

2024-07-30 15:00 UTC, za-arthur requested changes

2024-07-30 15:00 UTC, za-arthur commented on src/pg_type_template/templates/src/type_name.c.jinja
> +	ArrayType *array;
```suggestion
```

2024-07-30 15:00 UTC, za-arthur commented on src/pg_type_template/templates/src/type_name.c.jinja
> +    PG_RETURN_ARRAYTYPE_P(array);
I think the proper fix would be:
```suggestion
    PG_RETURN_DATUM(makeArrayResult(astate, CurrentMemoryContext));
```

2024-07-31 08:39 UTC, za-arthur approved these changes

2024-07-31 08:43 UTC, ridvankorkmaz commented
Merging this, and I will create ticket in for KPIS

2024-07-31 08:43 UTC, merged